// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChDD2fM4dKbHpkqSgSNwll6ojSSlcKJNM',
    appId: '1:651666429324:web:7700d9902b629f47d972a9',
    messagingSenderId: '651666429324',
    projectId: 'shopverse-16af2',
    authDomain: 'shopverse-16af2.firebaseapp.com',
    storageBucket: 'shopverse-16af2.firebasestorage.app',
    measurementId: 'G-J4CFD935TD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi0Xr6mCnRO7J-nWOHSgYvypkqbZIF55Y',
    appId: '1:651666429324:android:0439c226ab91fa8dd972a9',
    messagingSenderId: '651666429324',
    projectId: 'shopverse-16af2',
    storageBucket: 'shopverse-16af2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlIn-UxnTq72noNW_OB_uod8yeIGHIPrk',
    appId: '1:651666429324:ios:a192915dba218bafd972a9',
    messagingSenderId: '651666429324',
    projectId: 'shopverse-16af2',
    storageBucket: 'shopverse-16af2.firebasestorage.app',
    androidClientId: '651666429324-esos7vg724rt7q3qqlqai94o83bddvon.apps.googleusercontent.com',
    iosClientId: '651666429324-q2d0um7uv3h0c7lddkvo8nrb5mh330d1.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopverse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlIn-UxnTq72noNW_OB_uod8yeIGHIPrk',
    appId: '1:651666429324:ios:a192915dba218bafd972a9',
    messagingSenderId: '651666429324',
    projectId: 'shopverse-16af2',
    storageBucket: 'shopverse-16af2.firebasestorage.app',
    androidClientId: '651666429324-esos7vg724rt7q3qqlqai94o83bddvon.apps.googleusercontent.com',
    iosClientId: '651666429324-q2d0um7uv3h0c7lddkvo8nrb5mh330d1.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopverse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChDD2fM4dKbHpkqSgSNwll6ojSSlcKJNM',
    appId: '1:651666429324:web:c34dbf09ae91554dd972a9',
    messagingSenderId: '651666429324',
    projectId: 'shopverse-16af2',
    authDomain: 'shopverse-16af2.firebaseapp.com',
    storageBucket: 'shopverse-16af2.firebasestorage.app',
    measurementId: 'G-6SEDSPSBHB',
  );
}
